spring:
  application:
    name: ichitabi

  devtools:
    livereload:
      enabled: true

  config:
    import: optional:classpath:application-env.properties

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

file:
  upload:
    itemImgLocation: C:/shop/item
    uploadPath: file:///C:/shop/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml